'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const source=fs.readFileSync('dist/assets/safimaint-fiix-v85.js','utf8');
const css=fs.readFileSync('dist/assets/safimaint-fiix-v85.css','utf8');
const index=fs.readFileSync('dist/index.html','utf8');
const worker=fs.readFileSync('dist/service-worker.js','utf8');
const config=fs.readFileSync('dist/assets/safimaint-00-config.js','utf8');

for(const label of ['Dashboard','Maintenance','Notifications','Assets','Supplies','Purchasing','Reports','Settings']) assert.match(source,new RegExp(label));
for(const child of ['Parts & supplies','Current stock','Cycle counts','Stock history','BOM groups','Businesses']) assert.match(source,new RegExp(child));
assert.match(css,/grid-template-columns:196px/);
assert.match(css,/\.v85-sub/);
assert.match(css,/\.v85-table/);
assert.match(source,/data-v85-toggle/);
assert.match(source,/data-v85-toggle-store/);
assert.match(source,/data-v85-search/);
assert.match(source,/data-v85-category/);
assert.match(source,/data-action="global-stock-move"/);
assert.match(source,/data-action="add-part"/);
assert.match(source,/ui\.s80SupplyMode==='record'/);
assert.doesNotMatch(source,/Create purchase order/i);
assert.match(index,/safimaint-fiix-v85\.css\?v=85/);
assert.match(index,/safimaint-fiix-v85\.js\?v=85/);
assert.match(worker,/const CACHE='safimaint-fiix-v85'/);
assert.match(worker,/safimaint-fiix-v85\.css/);
assert.match(worker,/safimaint-fiix-v85\.js/);
assert.match(config,/9\.9\.1-fiix-desktop-shell/);
console.log('Supplies v85 Fiix-style shell and stock workspace checks passed.');
