'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require('playwright');
const {startPreview}=require('./preview_server.cjs');
async function main(){
  const {server,url}=await startPreview();let browser;
  try{
    browser=await chromium.launch({headless:true,...(process.env.SAFIMAINT_BROWSER_PATH?{executablePath:process.env.SAFIMAINT_BROWSER_PATH}:{})});
    const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto(url+'/?device=1&presentation=1');await page.waitForSelector('.rb-home');
    assert.equal(await page.locator('link[rel=stylesheet]:not([media])').count(),1,'Exactly one active design system');
    assert.equal(Number(await page.locator('[data-rb-queue="open"] strong').innerText()),await page.evaluate(()=>safiRebuildAttention().open.length));
    await page.locator('.rb-measure[data-rb-queue=overdue]').click();
    assert.equal(await page.locator('.rb-home-queue [data-rb-work]').count(),Math.min(8,await page.evaluate(()=>safiRebuildAttention().overdue.length)));
    const routes=['dashboard','work-orders','requests','pm','calendar','assets','facilities','equipment','tools','meters','downtime','inventory','stock-locations','batch-stock','counts','transactions','bom-groups','businesses','planning','reports','people','roles','permissions','sites','notifications','audit','sync-center','security','task-groups','projects','workflows'];
    routes.push('purchase-requests','purchase-orders','receipts','rfqs','analytics','groups','asset-insights');
    fs.mkdirSync('.test-tmp/rebuild',{recursive:true});
    for(const width of [1440,390]){
      await page.setViewportSize({width,height:1000});
      for(const route of routes){
        await page.evaluate(route=>go(route),route);
        assert.ok((await page.locator('#appView').innerText()).length>50,'Empty route '+route);
        assert.equal(await page.locator('#navigation [aria-current=page]').count(),1,'Single active destination '+route);
        await page.screenshot({path:'.test-tmp/rebuild/'+route+'-'+width+'.png',fullPage:true});
        const overflowing=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);
        if(overflowing)console.log(await page.evaluate(()=>[...document.querySelectorAll('#appView *')].filter(el=>el.getBoundingClientRect().right>innerWidth+1).slice(0,12).map(el=>({tag:el.tagName,class:el.className,width:el.getBoundingClientRect().width,text:el.textContent.slice(0,50)}))));
        assert.ok(!overflowing,'Viewport overflow '+route+' '+width);
      }
    }
    await page.setViewportSize({width:1440,height:1000});
    await page.evaluate(()=>go('people'));
    await page.locator('[data-rb-search=people]').fill('zz-no-user');
    assert.equal(await page.locator('[data-rb-user]').count(),0);
    await page.locator('[data-rb-clear-users]').click();
    const profile=await page.evaluate(()=>state.users.find(u=>u.id!==CURRENT_USER));
    await page.locator('[data-rb-user="'+profile.id+'"]').first().click();
    assert.equal(await page.locator('#modal input[name=email]').getAttribute('readonly'),'');
    await page.locator('#modal input[name=jobTitle]').fill('Acceptance technician');
    await page.locator('#modalForm button[type=submit]').click();
    assert.equal(await page.evaluate(id=>getUser(id).jobTitle,profile.id),'Acceptance technician');
    await page.evaluate(()=>{state.purchasingSettings.requirePoApproval=true;state.purchasingSettings.poApprovalThreshold=0;go('purchase-orders');});
    const orderPart=await page.evaluate(()=>state.parts[0]);
    const stockBeforeOrder=await page.evaluate(id=>getPart(id).locations.reduce((n,l)=>n+Number(l.onHand||0),0),orderPart.id);
    await page.locator('[data-action=manual-po]').click();
    await page.locator('#modal [name=partId]').selectOption(orderPart.id);
    await page.locator('#modal [name=qty]').fill('2');
    await page.locator('#modal [name=unitCost]').fill('10');
    await page.locator('#modalForm button[type=submit]').click();
    const newOrder=await page.evaluate(()=>state.purchaseOrders[0]);
    assert.equal(newOrder.status,'Awaiting Approval');
    await page.locator('[data-v56-approve-po="'+newOrder.id+'"]').click();
    await page.locator('[data-v56-place-po="'+newOrder.id+'"]').click();
    await page.locator('[data-receive-po="'+newOrder.id+'"]').click();
    await page.locator('#modal [name=line_0]').fill('1');
    await page.locator('#modalForm button[type=submit]').click();
    assert.equal(await page.evaluate(id=>state.purchaseOrders.find(p=>p.id===id).status,newOrder.id),'Partially received');
    await page.locator('[data-receive-po="'+newOrder.id+'"]').click();
    await page.locator('#modalForm button[type=submit]').click();
    assert.equal(await page.evaluate(id=>state.purchaseOrders.find(p=>p.id===id).status,newOrder.id),'Received');
    assert.equal(await page.evaluate(id=>getPart(id).locations.reduce((n,l)=>n+Number(l.onHand||0),0),orderPart.id),stockBeforeOrder+2);
    assert.equal(await page.evaluate(id=>state.receipts.filter(r=>r.purchaseOrderId===id).length,newOrder.id),2);
    await page.evaluate(()=>go('pm'));
    await page.locator('[data-rb-search=pm]').fill('zz-no-plan');
    assert.equal(await page.locator('[data-v52-edit-pm]').count(),0);
    await page.locator('[data-rb-search=pm]').fill('');
    const originalUser=await page.evaluate(()=>CURRENT_USER);
    await page.evaluate(()=>{state.roles.push({id:'QA-NONE',name:'No permissions',permissions:[]});state.users.push({id:'QA-USER',name:'Restricted test user',roleId:'QA-NONE',active:true,groupIds:[],siteIds:[]});CURRENT_USER='QA-USER';});
    for(const [route,selector] of [['people','[data-rb-user]'],['work-orders','[data-rb-work]'],['pm','[data-v52-edit-pm]'],['asset-insights','[data-rb-asset]']]){
      await page.evaluate(route=>go(route),route);
      assert.equal(await page.locator('#appView '+selector).count(),0,'Restricted register leaks data: '+route);
    }
    await page.evaluate(id=>{CURRENT_USER=id;state.users=state.users.filter(u=>u.id!=='QA-USER');state.roles=state.roles.filter(r=>r.id!=='QA-NONE');},originalUser);
    await page.evaluate(()=>{ui.assetView='hierarchy';go('assets')});
    const asset=await page.evaluate(()=>state.assets.find(a=>a.type==='Equipment'));
    await page.locator('[data-rb-search=assets]').fill(asset.code);
    assert.ok(await page.locator('[data-rb-asset="'+asset.id+'"]').count());
    await page.locator('[data-rb-asset="'+asset.id+'"]').click();await page.waitForSelector('.ar72-record');
    await page.screenshot({path:'.test-tmp/rebuild/asset-record-1440.png',fullPage:true});
    await page.evaluate(()=>{ui.s80SupplyMode='list';go('inventory')});
    assert.ok(await page.locator('[data-rb-part]').count()>=await page.evaluate(()=>state.parts.length));
    const locationId=await page.locator('[data-rb-part-toggle][aria-expanded=true]').first().getAttribute('data-rb-part-toggle');
    const location=page.locator('[data-rb-part-toggle="'+locationId+'"][aria-expanded]');
    await location.click();assert.equal(await location.getAttribute('aria-expanded'),'false');
    await page.locator('[data-rb-part-view=list]').click();
    await page.locator('[data-rb-sort="parts-list|stock"]').click();
    const sortedStock=await page.locator('[data-rb-grid="parts-list"] tbody tr').evaluateAll(rows=>rows.map(row=>Number(row.children[4].textContent.split(' ')[0])));
    assert.deepEqual(sortedStock,sortedStock.slice().sort((a,b)=>a-b),'Stock sort uses numeric values');
    await page.locator('[data-rb-columns="parts-list"]').first().click();
    await page.locator('#modal input[name=column][value=supplier]').check();
    await page.locator('#modal input[name=column][value=aisle]').uncheck();
    await page.locator('#modalForm button[type=submit]').click();
    assert.ok((await page.locator('[data-rb-grid="parts-list"] thead').innerText()).includes('Preferred supplier'));
    assert.ok(!(await page.locator('[data-rb-grid="parts-list"] thead').innerText()).includes('Aisle'));
    await page.locator('[data-rb-size="parts-list"]').selectOption('50');
    assert.equal(await page.evaluate(()=>ui.rbGrid['parts-list'].size),50);
    await page.locator('[data-rb-select=parts]').first().check();
    assert.equal(await page.evaluate(()=>ui.rbSelected.parts.length),1);
    const downloaded=page.waitForEvent('download');await page.locator('[data-rb-export=parts]').click();
    assert.ok((await downloaded).suggestedFilename().startsWith('safimaint-parts-'));
    await page.locator('[data-rb-select=parts]').first().uncheck();
    assert.equal(await page.evaluate(()=>ui.rbSelected.parts.length),0);
    await page.locator('[data-sm-show-sources=supplies]').first().click();
    assert.equal(await page.locator('#modal [data-sm-attention=part]').count(),await page.evaluate(()=>safiNavigationAttention('supplies').length));
    await page.evaluate(()=>closeModal());
    await page.locator('[data-rb-part-filter=low]').click();assert.equal(await page.locator('[data-rb-part]').count(),await page.evaluate(()=>safiRebuildAttention().low.length));
    await page.locator('[data-rb-part-filter=all]').click();
    const part=await page.evaluate(()=>state.parts[0]);
    await page.locator('[data-rb-search=parts]').fill(part.code);assert.equal(await page.locator('[data-rb-part]').count(),1);
    await page.locator('[data-rb-part="'+part.id+'"]').click();await page.waitForSelector('[data-s80-record-form]');
    await page.screenshot({path:'.test-tmp/rebuild/part-record-1440.png',fullPage:true});
    await page.locator('[data-s80-record-form] [name=name]').fill(part.name+' draft');
    await page.locator('[data-s80-back]').click();await page.locator('[data-rb-part="'+part.id+'"]').first().click();
    assert.equal(await page.locator('[data-s80-record-form] [name=name]').inputValue(),part.name+' draft');
    await page.locator('[data-s93-discard]').click();
    await page.evaluate(()=>go('work-orders'));
    await page.locator('[data-rb-search=work]').fill('zz-no-record');assert.equal(await page.locator('[data-rb-work]').count(),0);
    await page.locator('[data-rb-search=work]').fill('');await page.locator('[data-rb-work]').first().click();await page.waitForSelector('#modal[open]');await page.screenshot({path:'.test-tmp/rebuild/work-record-1440.png',fullPage:true});
    await page.evaluate(()=>closeModal());
    const requestId=await page.evaluate(()=>{const r={id:'REQ-ACCEPT',summary:'Board inspection request',assetId:state.assets.find(a=>a.type==='Equipment')?.id||state.assets[0].id,status:'Requested',urgency:'Normal',requester:'Acceptance',createdAt:iso(),description:'Inspect equipment',history:[]};state.requests.push(r);go('requests');return r.id});
    await page.locator('[data-v52-triage-request="'+requestId+'"]').click();
    await page.locator('#modalForm [name="note"]').fill('Approved during board workflow rehearsal');
    await page.locator('#modalForm button[type="submit"]').click();
    assert.equal(await page.evaluate(id=>state.requests.find(r=>r.id===id).status,requestId),'Converted');
    assert.ok(await page.evaluate(id=>state.workOrders.some(w=>w.source===id),requestId));
    const generated=await page.evaluate(()=>{const asset=state.assets.find(a=>a.type==='Equipment')||state.assets[0];state.scheduledMaintenance.push({id:'PM-BOARD-ACCEPT',name:'Board recurring inspection',assetIds:[asset.id],scheduleMode:'Floating',status:'Active',triggerLogic:'ANY',triggers:[{id:'TRG-BOARD',type:'Time',active:true,nextDue:day(0),description:'Every 7 days'}],taskTemplate:[],requiredParts:[]});go('pm');return state.workOrders.length});
    await page.locator('[data-generate-pm="PM-BOARD-ACCEPT"]').click();
    assert.equal(await page.evaluate(()=>state.workOrders.length),generated+1);
    await page.locator('[data-generate-pm="PM-BOARD-ACCEPT"]').click();
    assert.equal(await page.evaluate(()=>state.workOrders.length),generated+1,'PM created duplicate open work');
    await page.evaluate(()=>go('work-orders'));
    const count=await page.locator('[data-rb-work]').count();assert.ok(count>0);
    await page.locator('[data-rb-search="work"]').fill('no-such-work-xyz');
    assert.equal(await page.locator('[data-rb-work]').count(),0);
    await page.locator('[data-rb-search="work"]').fill('');
    assert.equal(await page.locator('[data-rb-work]').count(),count);
    await page.evaluate(()=>showNewWork());
    assert.equal(await page.locator('.safi-advanced-fields').count(),1);
    await page.locator('#modalForm [name="title"]').fill('Acceptance inspection');
    await page.locator('#modalForm [name="type"]').selectOption('Preventive');
    await page.locator('#modalForm [name="assetIds"]').first().check();
    await page.locator('#modalForm button[type="submit"]').click();
    await page.waitForFunction(()=>state.workOrders.some(w=>w.title==='Acceptance inspection'));
    const inventory=await page.evaluate(()=>{
      closeModal();const part=state.parts.find(p=>p.locations.some(l=>l.active!==false&&l.onHand>=2));
      const location=part.locations.find(l=>l.active!==false&&l.onHand>=2);
      const before=JSON.stringify({parts:state.parts,lots:state.inventoryLots,transactions:state.stockTransactions});
      let rejected=false;try{postStock(part.id,'Issue',1000000,location.storeId,location.bin)}catch(_error){rejected=true}
      const unchanged=before===JSON.stringify({parts:state.parts,lots:state.inventoryLots,transactions:state.stockTransactions});
      const quantity=location.onHand,work=state.workOrders.find(w=>w.title==='Acceptance inspection');
      postStock(part.id,'Issue',1,location.storeId,location.bin,{workOrderId:work.id});
      const issued=location.onHand===quantity-1&&work.parts.find(l=>l.partId===part.id)?.actual===1;
      return {rejected,unchanged,issued};
    });
    assert.deepEqual(inventory,{rejected:true,unchanged:true,issued:true});
    await page.evaluate(()=>{
      const work=state.workOrders.find(w=>w.title==='Acceptance inspection');
      work.actualHours=1;work.labor=[{id:'LAB-ACCEPT',userId:CURRENT_USER,hours:1}];
      state.scheduledMaintenance.push({id:'PM-ACCEPT',name:'Floating acceptance',assetIds:work.assetIds,
        scheduleMode:'Floating',status:'Active',awaitingCompletionWorkOrderId:work.id,nextDue:day(-1),
        triggers:[{id:'TRG-ACCEPT',type:'Time',active:true,description:'Every 7 days',nextDue:day(-1)}]});
      openWorkDrawer(work.id);
    });
    await page.locator('[data-v44-status]').selectOption('Completed');
    await page.locator('#modalForm [name="completionNote"]').fill('Inspection completed and verified.');
    await page.locator('#modalForm button[type="submit"]').click();
    const plan=await page.evaluate(()=>{
      const pm=state.scheduledMaintenance.find(p=>p.id==='PM-ACCEPT');
      return {waiting:pm.awaitingCompletionWorkOrderId,ready:safiPmReady(pm),sameDate:pm.nextDue===pm.triggers[0].nextDue};
    });
    assert.deepEqual(plan,{waiting:null,ready:false,sameDate:true});
    await page.setViewportSize({width:390,height:844});
    await page.evaluate(()=>{ui.s80SupplyMode='list';go('inventory')});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Mobile inventory overflows');
    await page.locator('[data-rb-part]').first().click();
    await page.waitForSelector('.s93-stock-left');
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Mobile part record overflows');
    await page.screenshot({path:'.test-tmp/supply-record-mobile.png',fullPage:true});
    await page.evaluate(()=>go('dashboard'));
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Mobile page overflows');
    assert.ok((await page.locator('#sidebar').boundingBox()).x<0,'Mobile navigation should start closed');
    await page.locator('#menuButton').click();assert.equal(await page.locator('#sidebar').evaluate(e=>e.classList.contains('open')),true);
    await page.locator('#scrim').click({position:{x:370,y:400}});
    await page.waitForFunction(()=>navigator.serviceWorker?.controller);
    await page.context().setOffline(true);await page.reload({waitUntil:'domcontentloaded'});
    await page.waitForFunction(()=>typeof window.SafiMaintainDemo==='object');
    assert.ok(await page.evaluate(()=>state.workOrders.some(w=>w.title==='Acceptance inspection')),'Offline reload lost device records');
    assert.equal(await page.evaluate(async()=>{try{await fetch('/api/health');return true}catch(_error){return false}}),false,'API must not be served from the shell cache');
    await page.context().setOffline(false);
    assert.deepEqual(errors,[]);
    const fresh=await browser.newPage();fresh.on('pageerror',error=>errors.push(error.message));
    await fresh.goto(url);await fresh.locator('#firstRunForm [name="name"]').fill('Acceptance operator');
    await fresh.locator('#firstRunForm [name="email"]').fill('operator@example.com');
    await fresh.locator('#firstRunForm [name="site"]').fill('Acceptance site');
    await fresh.locator('#firstRunForm button[type="submit"]').click();
    await fresh.waitForFunction(()=>state.meta.onboardingComplete);
    await fresh.reload();
    await fresh.waitForFunction(()=>state.meta.onboardingComplete);
    assert.deepEqual(await fresh.evaluate(()=>({site:state.sites[0].name,parts:state.parts.length,demo:!!state.meta.demo})),{site:'Acceptance site',parts:0,demo:false});
    await fresh.goto(url+'/?device=1&presentation=1');
    await fresh.waitForSelector('.rb-home');
    assert.equal(await fresh.evaluate(()=>state.meta.demo),true);
    assert.ok(await fresh.evaluate(()=>state.parts.length>0&&state.workOrders.length>0));
    await fresh.reload();await fresh.waitForSelector('.rb-home');
    assert.equal(await fresh.evaluate(()=>state.meta.demo),true);
    await fresh.goto(url);await fresh.waitForSelector('.rb-home');
    assert.deepEqual(await fresh.evaluate(()=>({site:state.sites[0].name,parts:state.parts.length,demo:!!state.meta.demo})),{site:'Acceptance site',parts:0,demo:false});
    await fresh.close();assert.deepEqual(errors,[]);
    assert.deepEqual(errors,[],'Browser errors');
    console.log('PASS: rebuilt UI, '+routes.length+' pages at desktop/mobile sizes, permission-gated registers, navigation, dashboard drill-down, asset search/record, sortable/customizable parts, user profile editing, work search/record, request triage, creation/closure, PM scheduling/filtering, atomic stock issue, offline reload and isolated demo persistence.');
  }finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));}
}
main().catch(e=>{console.error(e);process.exitCode=1});



